### ISSUE TITLE
Issue to trigger new releases

### ISSUE THREAD

**Issue by OkonSamuel** [alan-turing-institute/MLJClusteringInterface.jl#1]
@JuliaRegistrator register

**Comment by OkonSamuel** [comment]
@JuliaRegistrator register

**Comment by OkonSamuel** [comment]
@JuliaRegistrator register

**Comment by OkonSamuel** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register

release notes:

- extend MLJModelInterface to 1.0
