### ISSUE TITLE
Add remaining static clustering models

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJClusteringInterface.jl#19]
https://juliastats.org/Clustering.jl/stable/

@OkonSamuel

**Comment by Yuan-Ru-Lin** [comment]
Hi @ablaom Affinity Propagation is used in the study that I am working on, but its interface hasn't been implemented in this package yet. Is there anything I should pay attention to if I have time to implement it next week?

**Comment by ablaom** [comment]
Many thanks for the offer of help!

My only comment is that this looks like a `Static` model, as it cannot generalise to new data instances (like KMeans can), correct?

Assuming that is the case, you can use DBSCAN as a template. See [here](https://juliaai.github.io/MLJ.jl/dev/models/DBSCAN_Clustering/) for the workflow you would be supporting.

**Comment by Yuan-Ru-Lin** [comment]
It turns out I have some time in the weekend so I have drafted a PR (#28).

As for your question, the model looks a lot like `KMedoids` so I used it as a template and even directly extended the existing `MMI.predict` so that it works with `AffinityPropagation`. (I only realized it's `Unsupervised` instead of `Static` after I started working on it so sorry it's the wrong topic to talk about the model!)

**Comment by ablaom** [comment]
Mmm. If it's a truly static model (no generalisation) you can't use KMedoids without some changes: 

-  model type is `Static`
- `fit` has not training data (all the work is done by `predict`, which does of course need data)

**Comment by Yuan-Ru-Lin** [comment]
Judging from the algorithm of the model, I don't think the model can generalize to new data instances. (One can determine which exemplar a datum is closest to, but that's not necessarily a reasonable classifier for out-of-sample data.) It's better to implement it as a `Static` model. I'll do it later.

**Comment by ablaom** [comment]
Great. Ping me when you are ready for review. No rush.

**Comment by ablaom** [comment]
This is now merged. For @ablaom to do:
- [x] Tag new release of this pkg
- [x] Update model registry
- [x] Add to list of models at MLJ docs
- [x] Add model descriptor at MLJ docs
- [x] Fix `input_scitype`

cc @Yuan-Ru-Lin

**Comment by Yuan-Ru-Lin** [comment]
I have existing PRs addressing some of the unchecked boxes

One is https://github.com/JuliaAI/MLJModels.jl/pull/574, the other is https://github.com/JuliaAI/MLJ.jl/pull/1147.

EDIT: add a PR

**Comment by ablaom** [comment]
Closed as complete.
