### ISSUE TITLE
 Final integration steps

### ISSUE THREAD

**Issue by OkonSamuel** [alan-turing-institute/MLJClusteringInterface.jl#2]
- [x] Add travis CI

- [x] Register `MLJClusteringInterface`

- [x] Create a `MLJModels` branch `cluster-migration` that removes `Clustering` glue code and updates the registry to reflect the migration

- [x] Locally test updated registry in `cluster-migration` finds `MLJClusteringInterface.jl`

Merge multi-stats-migration into dev and master branches of MLJModels and tag a new release.
@cc @ablaom

**Comment by ablaom** [comment]
Waiting for merge of https://github.com/JuliaRegistries/General/pull/23287 (3 day stand-down period for new package 😢)
